config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/home'      , to: 'static_pages#home'
  get '/contest'   , to: 'static_pages#contest'
  get '/world_tour', to: 'static_pages#world_tour'

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  get    '/login' , to: 'sessions#new'
  post   '/login' , to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contest.rb
class Contest < ApplicationRecord
  validates :name, presence: true
  validates :start_epoch_second, presence: true
  validates :duration_second, presence: true
  validates :title, presence: true
  validates :rate_change, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid name/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contest
  end

  def world_tour
  end

  def links
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to @user
      flash[:success] = 'Welcome to AtCoder Standings!'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    # FIXME: 現状、エラーとなる入力に対しても、更新ができてしまう
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user)
            .permit(:name, :atcoder_id, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = 'Please log in.'
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
footer
  span
    | Copyright © 2019-2020 hiro_hiro, All Rights Reserved.

app/views/layouts/_header.html.slim
header.navbar.navbar-expand-lg.fixed-top.navbar-inverse.navbar-dark.bg-dark
  .container
    = link_to "AtCoder Standings", root_path, id:"logo", class: "nav-brand"

  nav
    ul.nav.navbar-nav.navbar-right
      li.nav-item
        = link_to "Home", root_path, class: "nav-link"
      li.nav-item
        = link_to "Contest", contest_path, class: "nav-link"
      li.nav-item
        = link_to "World Tour", world_tour_path, class: "nav-link"

      - if logged_in?
        li.nav-item
          = link_to "Users", users_path, class: "nav-link"
        li.nav-item
          = link_to "#{current_user.name}", edit_user_path(current_user), class: "nav-link"

      li.nav-item
        = link_to "Links", '#', {class: "nav-link dropdown-toggle", id: "relatedLinks", "data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false"}

        .dropdown-menu[aria-labelledby="relatedLinks"]
          = link_to "AtCoder", "https://atcoder.jp/", {class: "dropdown-item", target: "_blank", rel: "noopener"}
          = link_to "GitHub", "https://github.com/KATO-Hiro/AtCoderStandings", {class: "dropdown-item", target: "_blank", rel: "noopener"}
          = link_to "@hiro_hiro", "https://twitter.com/k_hiro1818", {class: "dropdown-item", target: "_blank", rel: "noopener"}

      - if logged_in?
        li.nav-item
          = link_to "Log out", logout_path, method: :delete, class: "nav-link"
      - else
        li.nav-item
          = link_to "Log in", login_path, class: "nav-link"

app/views/layouts/_rails_default.html.slim
meta[charset="utf-8"]
= csrf_meta_tags
= csp_meta_tag
= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_replay_table_body.html.slim
script[type="text/javascript"]
  |
    replayTable.magic()

app/views/layouts/_replay_table_head.html.slim
script[type="text/javascript" src="https://d3js.org/d3.v4.min.js" crossorigin="anonymous"]
script[type="text/javascript" src="https://unpkg.com/replay-table/dist/replay-table.min.js" crossorigin="anonymous"]
link[rel="stylesheet" type="text/css" href="https://unpkg.com/replay-table/dist/replay-table.css" crossorigin="anonymous"]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AtCoder Standings

    = render 'layouts/rails_default'
    = render 'layouts/replay_table_head'
  body
    = render 'layouts/header'

    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
          = message

      = yield

    = render 'layouts/replay_table_body'
    = render 'layouts/footer'

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  .[id="error_explanation"]
    .alert.alert-danger
      | The form contains #{pluralize(@user.errors.count, "error")}

    ul
      - @user.errors.full_messages.each do |msg|
        li
          = msg

app/views/static_pages/contest.html.slim
h2
  | Contest Standings

app/views/static_pages/home.html.slim
h1
  = javascript_pack_tag 'hello_react'

app/views/static_pages/index.html.slim
h1
  = javascript_pack_tag 'hello_react'

app/views/static_pages/replay.html.slim
h2
  | Replay contest

.replayTable[id="replay-world-tour-final"
  data-source="csv/world_tour_final/world_tour_final_2019.csv"
  data-transformer="pointsTable"
  data-insert-start-round="Start"
  data-extra-columns-number="2,3"
  data-columns="position,item,Country,Rating,points,points.change"
  data-labels="#,Handle,Country,Rating,GP30 Points"
  data-animation-speed=0.5
  ]

app/views/static_pages/world_tour.html.slim
h2
  | Replay contest

.replayTable[id="replay-world-tour-final"
  data-source="csv/world_tour_final/world_tour_final_2019.csv"
  data-transformer="pointsTable"
  data-insert-start-round="Start"
  data-extra-columns-number="2,3"
  data-columns="position,item,Country,Rating,points,points.change"
  data-labels="#,Handle,Country,Rating,GP30 Points"
  data-animation-speed=0.5
  ]

app/views/users/_form.html.slim
= form_for(@user) do |f|
  = render 'shared/error_messages'

  = f.label :name
  = f.text_field :name, class: 'form-control'

  = f.label :atcoder_id, "AtCoder ID"
  = f.text_field :atcoder_id, class: 'form-control'

  = f.label :password
  = f.password_field :password, class: 'form-control'

  = f.label :password_confirmation, "Confirmation"
  = f.password_field :password_confirmation, class: 'form-control'

  = f.submit yield(:button_text), class: "btn btn-primary"

app/views/users/_user.html.slim
li
  = link_to user.name, user

  - if current_user.admin? && !current_user?(user)
    = " | "
    = link_to 'delete', user, method: :delete,
                              data: { confirm: 'You sure?' }

app/views/users/edit.html.slim
- provide(:button_text, 'Save changes')

h2
  | Update your profile

.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/users/index.html.slim
h2
  | All users

ul.users
  = render @users

  = paginate @users

app/views/users/new.html.slim
- provide(:button_text, 'Create my account')

h2
  | Sign up

.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/users/show.html.slim
= @user.name
= @user.atcoder_id
= @user.created_at
= @user.updated_at